default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.db[:host] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  pool: 5

development:
  <<: *default
  database: my_app_2020_development


test:
  <<: *default
  database: my_app_2020_test
